command! -nargs=0 PMCreateProject lua require("projectmanager").createProject()
command! -nargs=0 PMOpenProject lua require("projectmanager").openProject()
command! -nargs=0 PMProjects lua require("projectmanager").projects() 
command! -nargs=0 PMTemplates lua require("projectmanager").templates() 
command! -nargs=0 PMClearRecentProjects lua require("projectmanager").clearRecentProjects()
